const mockup = [
  {
    id: 1,
    name: "Wireless Mouse",
    category: "Electronics",
    price: 29.99,
    inStock: true,
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 89.99,
    inStock: true,
  },
  {
    id: 3,
    name: "Gaming Headset",
    category: "Electronics",
    price: 59.99,
    inStock: false,
  },
  {
    id: 4,
    name: "USB-C Hub",
    category: "Accessories",
    price: 24.99,
    inStock: true,
  },
  {
    id: 5,
    name: "Portable Charger",
    category: "Accessories",
    price: 19.99,
    inStock: true,
  },
  {
    id: 6,
    name: "Smartphone Stand",
    category: "Accessories",
    price: 9.99,
    inStock: true,
  },
  {
    id: 7,
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 49.99,
    inStock: false,
  },
  {
    id: 8,
    name: "Noise Cancelling Earbuds",
    category: "Electronics",
    price: 99.99,
    inStock: true,
  },
  {
    id: 9,
    name: "Laptop Cooling Pad",
    category: "Accessories",
    price: 15.99,
    inStock: true,
  },
  {
    id: 10,
    name: "External Hard Drive",
    category: "Electronics",
    price: 74.99,
    inStock: true,
  },
  {
    id: 11,
    name: "LED Desk Lamp",
    category: "Home Office",
    price: 39.99,
    inStock: true,
  },
  {
    id: 12,
    name: "Ergonomic Chair",
    category: "Furniture",
    price: 149.99,
    inStock: false,
  },
  {
    id: 13,
    name: "Dual Monitor Stand",
    category: "Accessories",
    price: 59.99,
    inStock: true,
  },
  {
    id: 14,
    name: "4K Webcam",
    category: "Electronics",
    price: 129.99,
    inStock: true,
  },
  {
    id: 15,
    name: "Adjustable Standing Desk",
    category: "Furniture",
    price: 299.99,
    inStock: true,
  },
  {
    id: 16,
    name: "Whiteboard",
    category: "Office Supplies",
    price: 24.99,
    inStock: true,
  },
  {
    id: 17,
    name: "Wireless Charger",
    category: "Accessories",
    price: 19.99,
    inStock: true,
  },
  {
    id: 18,
    name: "Graphic Tablet",
    category: "Electronics",
    price: 89.99,
    inStock: false,
  },
  {
    id: 19,
    name: "Smart Light Bulb",
    category: "Home Automation",
    price: 14.99,
    inStock: true,
  },
  {
    id: 20,
    name: "Fitness Tracker",
    category: "Wearables",
    price: 49.99,
    inStock: true,
  },
];

module.exports = mockup