const mockup = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 25,
    isActive: true,
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    age: 30,
    isActive: false,
  },
  {
    id: 3,
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    age: 22,
    isActive: true,
  },
  {
    id: 4,
    name: "Diana Prince",
    email: "diana.prince@example.com",
    age: 28,
    isActive: true,
  },
  {
    id: 5,
    name: "Ethan Hunt",
    email: "ethan.hunt@example.com",
    age: 35,
    isActive: false,
  },
  {
    id: 6,
    name: "Fiona Carter",
    email: "fiona.carter@example.com",
    age: 27,
    isActive: true,
  },
  {
    id: 7,
    name: "George Baker",
    email: "george.baker@example.com",
    age: 31,
    isActive: false,
  },
  {
    id: 8,
    name: "Hannah Davis",
    email: "hannah.davis@example.com",
    age: 24,
    isActive: true,
  },
  {
    id: 9,
    name: "Ian Wright",
    email: "ian.wright@example.com",
    age: 29,
    isActive: true,
  },
  {
    id: 10,
    name: "Julia Roberts",
    email: "julia.roberts@example.com",
    age: 33,
    isActive: false,
  },
  {
    id: 11,
    name: "Kevin Harris",
    email: "kevin.harris@example.com",
    age: 26,
    isActive: true,
  },
  {
    id: 12,
    name: "Laura King",
    email: "laura.king@example.com",
    age: 32,
    isActive: false,
  },
  {
    id: 13,
    name: "Michael Scott",
    email: "michael.scott@example.com",
    age: 40,
    isActive: true,
  },
  {
    id: 14,
    name: "Nina Lopez",
    email: "nina.lopez@example.com",
    age: 23,
    isActive: true,
  },
  {
    id: 15,
    name: "Oscar Martinez",
    email: "oscar.martinez@example.com",
    age: 29,
    isActive: false,
  },
  {
    id: 16,
    name: "Paul Allen",
    email: "paul.allen@example.com",
    age: 34,
    isActive: true,
  },
  {
    id: 17,
    name: "Quinn Blake",
    email: "quinn.blake@example.com",
    age: 28,
    isActive: true,
  },
  {
    id: 18,
    name: "Rachel Adams",
    email: "rachel.adams@example.com",
    age: 27,
    isActive: false,
  },
  {
    id: 19,
    name: "Steve Rogers",
    email: "steve.rogers@example.com",
    age: 36,
    isActive: true,
  },
  {
    id: 20,
    name: "Tina Fey",
    email: "tina.fey@example.com",
    age: 30,
    isActive: false,
  },
];

module.exports = mockup